### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [berkileri/CMP3006-Lab-Work#1]
You may remove the line: `while(Wire.available()==0);` in the file "codes/lab9-i2cmaster.ino" because there is no such thing as waiting for something after a Wire.requestFrom().
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by berkileri** [comment]
Oh,  Wire.requestFrom() does the blocking already then, nice. Thank you!
